version: '3.8'

services:
  console:
    build:
      context: .
      args:
        - appName=${APPNAME}
        - appVersion=${APPVERSION}
        - port=${HTTPPORT}
    image: docker.pkg.github.com/edwardsuwirya/my-go-sql-docker/${APPNAME}:${APPVERSION}
    ports:
      - "${HTTPPORT}:${HTTPPORT}"
    environment:
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
      DBSCHEMA: ${DBSCHEMA}
      DBENGINE: ${DBENGINE}